name: Auto PR Title

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  set-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Set PR title
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
          REPOSITORY: ${{ github.repository }}
          TZ: Asia/Seoul

        run: |
          TODAY=$(date +"%Y/%m/%d")

          TITLE="[$BRANCH_NAME] $TODAY"

          echo "Repository: $REPOSITORY"
          echo "PR title: $TITLE"

          gh pr edit "$PR_NUMBER" \
            --repo "$REPOSITORY" \
            --title "$TITLE"
